### ISSUE TITLE
Grade first homework

### ISSUE THREAD

**Issue by belkin97** [belkin97/ASTR-119#3]
I would like for the TAs to grade my first homework assignment

@mattkwiecien

**Comment by matt-april** [comment]
Hi @belkin97 - for this first homework assignment, we want you to create an issue first on Github, then resolve it through a PR.  It looks like you have not created an issue.  Can you create an issue and resolve it to complete that part of the assignment (number 2 specifically)?  You don't need to necessarily resolve it through a PR, but in the future the homework may require you to.  Once that's done I can go ahead and grade your first-homework!  (See the assignment for more details)
