### ISSUE TITLE
Grade Homework-2

### ISSUE THREAD

**Issue by belkin97** [belkin97/ASTR-119#5]
Required files have been submitted to complete Homework-2 and are awaiting grading in astr-119-hw-2

@brucelaughlin

**Comment by matt-april** [comment]
Hi Filiberto!  You are in the Section A Lab, I'm the TA for the Section B Lab.  Could you please assign your TA (Bruce).  Thanks :)

**Comment by belkin97** [comment]
Sorry about that Matt!
